import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={cn("h-full antialiased w-full", "font-sans", geist.variable)}
    >
      <body className="min-h-screen flex flex-col items-center">
        <div className="w-full sm:min-w-[85%] md:min-w-[80%] min-h-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
