import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { AnimatedGridPattern } from "@/components/ui/animated-grid-pattern";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={cn("h-full antialiased w-full", "font-sans", geist.variable)}
    >
      <body className="min-h-screen flex flex-col items-center">
        <AnimatedGridPattern
          numSquares={30}
          maxOpacity={0.1}
          duration={3}
          repeatDelay={1}
          className={cn(
            "mask-[radial-gradient(800px_circle_at_center,white,transparent)]",
            // "inset-x-0 inset-y-[-30%] min-h-screen min-w-screen skew-y-12",
          )}
        />
        <div className="w-full sm:min-w-[85%] md:min-w-[80%] max-h-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
